kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
    name: local-storage
    annotations:
      storageclass.kubernetes.io/is-default-class: "true"
provisioner: kubernetes.io/portworx-volume
parameters:
   repl: "3"
   io_profile: "db_remote"
